<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class PeerPlayer {
	private $peerplayer_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'peerplayer_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'peerplayer_page_init' ) );
	}

	public function peerplayer_add_plugin_page() {
		add_options_page(
			'Peer Player', // page_title
			'Peer Player', // menu_title
			'manage_options', // capability
			'peerplayer', // menu_slug
			array( $this, 'peerplayer_create_admin_page' ) // function
		);
	}

	public function peerplayer_create_admin_page() {
		$this->peerplayer_options = get_option( 'peerplayer_option_name' ); ?>

		<div class="wrap">
			<h2>Peer Player</h2>
            <h3>Shortcode Instructions:</h3>
            <p>[peerplayer url="" autoplay="true" muted="false" watermark=""]</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'peerplayer_option_group' );
					do_settings_sections( 'peerplayer-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function peerplayer_page_init() {
		register_setting(
			'peerplayer_option_group', // option_group
			'peerplayer_option_name', // option_name
			array( $this, 'peerplayer_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'peerplayer_setting_section', // id
			'Settings', // title
			array( $this, 'peerplayer_section_info' ), // callback
			'peerplayer-admin' // page
		);

		// add_settings_field(
		// 	'peerplayer_api_token_0', // id
		// 	'Peerplayer API Token', // title
		// 	array( $this, 'peerplayer_api_token_0_callback' ), // callback
		// 	'peerplayer-admin', // page
		// 	'peerplayer_setting_section' // section
		// );

		add_settings_field(
			'video_player_1', // id
			'Video Player', // title
			array( $this, 'video_player_1_callback' ), // callback
			'peerplayer-admin', // page
			'peerplayer_setting_section' // section
		);
	}

	public function peerplayer_sanitize($input) {
		$sanitary_values = array();

		if ( isset( $input['video_player_1'] ) ) {
			$sanitary_values['video_player_1'] = $input['video_player_1'];
		}

		return $sanitary_values;
	}

	public function peerplayer_section_info() {

	}


	public function video_player_1_callback() {
		?> <select name="peerplayer_option_name[video_player_1]" id="video_player_1">
			<?php $selected = (isset( $this->peerplayer_options['video_player_1'] ) && $this->peerplayer_options['video_player_1'] === 'clappr') ? 'selected' : '' ; ?>
			<option value="clappr" <?php echo $selected; ?>>Clappr</option>
			<?php $selected = (isset( $this->peerplayer_options['video_player_1'] ) && $this->peerplayer_options['video_player_1'] === 'videojs') ? 'selected' : '' ; ?>
			<option value="videojs" <?php echo $selected; ?>>VideoJS</option>
			<!-- <?php $selected = (isset( $this->peerplayer_options['video_player_1'] ) && $this->peerplayer_options['video_player_1'] === 'flowplayer') ? 'selected' : '' ; ?>
			<option value="flowplayer" <?php echo $selected; ?>>Flow Player</option>
			<?php $selected = (isset( $this->peerplayer_options['video_player_1'] ) && $this->peerplayer_options['video_player_1'] === 'jwplayer') ? 'selected' : '' ; ?>
			<option value="jwplayer" <?php echo $selected; ?>>JW Player</option>
			<?php $selected = (isset( $this->peerplayer_options['video_player_1'] ) && $this->peerplayer_options['video_player_1'] === 'mediaelement') ? 'selected' : '' ; ?>
			<option value="mediaelement" <?php echo $selected; ?>>Media Element</option> -->
		</select>
		<?php
	}

}
if ( is_admin() )
	$peerplayer = new PeerPlayer();

/*
 * Retrieve this value with:
 * $peerplayer_options = get_option( 'peerplayer_option_name' ); // Array of All Options
 * $peerplayer_api_token_0 = $peerplayer_options['peerplayer_api_token_0']; // peerplayer API Token
 * $video_player_1 = $peerplayer_options['video_player_1']; // Video Player
 */
