/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class VadooTV {
	private $vadoo_tv_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'vadoo_tv_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'vadoo_tv_page_init' ) );
	}

	public function vadoo_tv_add_plugin_page() {
		add_options_page(
			'Vadoo TV', // page_title
			'Vadoo TV', // menu_title
			'manage_options', // capability
			'vadoo-tv', // menu_slug
			array( $this, 'vadoo_tv_create_admin_page' ) // function
		);
	}

	public function vadoo_tv_create_admin_page() {
		$this->vadoo_tv_options = get_option( 'vadoo_tv_option_name' ); ?>

		<div class="wrap">
			<h2>Vadoo TV</h2>
			<p>You can find your API Token by logging in to https://api.peervadoo.com/addapp</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'vadoo_tv_option_group' );
					do_settings_sections( 'vadoo-tv-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function vadoo_tv_page_init() {
		register_setting(
			'vadoo_tv_option_group', // option_group
			'vadoo_tv_option_name', // option_name
			array( $this, 'vadoo_tv_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'vadoo_tv_setting_section', // id
			'Settings', // title
			array( $this, 'vadoo_tv_section_info' ), // callback
			'vadoo-tv-admin' // page
		);

		add_settings_field(
			'vadootv_api_token_0', // id
			'VadooTV API Token', // title
			array( $this, 'vadootv_api_token_0_callback' ), // callback
			'vadoo-tv-admin', // page
			'vadoo_tv_setting_section' // section
		);
	}

	public function vadoo_tv_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['vadootv_api_token_0'] ) ) {
			$sanitary_values['vadootv_api_token_0'] = sanitize_text_field( $input['vadootv_api_token_0'] );
		}

		return $sanitary_values;
	}

	public function vadoo_tv_section_info() {

	}

	public function vadootv_api_token_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="vadoo_tv_option_name[vadootv_api_token_0]" id="vadootv_api_token_0" value="%s">',
			isset( $this->vadoo_tv_options['vadootv_api_token_0'] ) ? esc_attr( $this->vadoo_tv_options['vadootv_api_token_0']) : ''
		);
	}

}
if ( is_admin() )
	$vadoo_tv = new VadooTV();

/*
 * Retrieve this value with:
 * $vadoo_tv_options = get_option( 'vadoo_tv_option_name' ); // Array of All Options
 * $vadootv_api_token_0 = $vadoo_tv_options['vadootv_api_token_0']; // VadooTV API Token
 */
